import enum

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Гном и кристаллы"
TILE_SIZE = 64
PLAYER_SCALING = 0.5
CRYSTAL_SCALING = 0.5
HUNTER_SCALING = 0.5
OBSTACLE_SCALING = 0.5
PLAYER_SPEED = 300
HUNTER_SPEED = 150

GAME_MENU = 0
GAME_PLAYING = 1
GAME_WIN = 2
GAME_LOSE = 3

class FaceDirection(enum.Enum):
    LEFT = 0
    RIGHT = 1